jobs:

- job: Android_Tests
  variables:
    CI_Build: true
    SourceLinkEnabled: false

  pool:
    vmImage: 'macOS-10.14'

  steps:
  - checkout: self
    clean: true

  - bash: /bin/bash -c "sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_18_1"
    displayName: Select Xamarin Version

  - bash: |
      chmod +x $(build.sourcesdirectory)/build/android-uitest-run.sh
      $(build.sourcesdirectory)/build/android-uitest-run.sh

    displayName: Run Android Tests

    env:
      BUILD_SOURCESDIRECTORY: "$(build.sourcesdirectory)"
      BUILD_ARTIFACTSTAGINGDIRECTORY: "$(build.artifactstagingdirectory)"

  - bash: cp -r $(build.sourcesdirectory)/src/SamplesApp/SamplesApp.Droid/obj/Release/g/XamlCodeGenerator/ $(build.artifactstagingdirectory)
    condition: failed()
    displayName: "Copy generated XAML code"
 
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testRunTitle: 'Android Test Run'
      testResultsFormat: 'NUnit'
      testResultsFiles: '$(build.sourcesdirectory)/build/TestResult.xml'
      failTaskOnFailedTests: true

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: uitests-results
      ArtifactType: Container
